routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\WorksController;
use App\Http\Controllers\TasksController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::prefix('/')
    ->middleware('auth')
    ->group(function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);

        Route::resource('users', UserController::class);
        Route::get('all-clientes', [ClientesController::class, 'index'])->name(
            'all-clientes.index'
        );
        Route::post('all-clientes', [ClientesController::class, 'store'])->name(
            'all-clientes.store'
        );
        Route::get('all-clientes/create', [
            ClientesController::class,
            'create',
        ])->name('all-clientes.create');
        Route::get('all-clientes/{clientes}', [
            ClientesController::class,
            'show',
        ])->name('all-clientes.show');
        Route::get('all-clientes/{clientes}/edit', [
            ClientesController::class,
            'edit',
        ])->name('all-clientes.edit');
        Route::put('all-clientes/{clientes}', [
            ClientesController::class,
            'update',
        ])->name('all-clientes.update');
        Route::delete('all-clientes/{clientes}', [
            ClientesController::class,
            'destroy',
        ])->name('all-clientes.destroy');

        Route::get('all-works', [WorksController::class, 'index'])->name(
            'all-works.index'
        );
        Route::post('all-works', [WorksController::class, 'store'])->name(
            'all-works.store'
        );
        Route::get('all-works/create', [
            WorksController::class,
            'create',
        ])->name('all-works.create');
        Route::get('all-works/{works}', [WorksController::class, 'show'])->name(
            'all-works.show'
        );
        Route::get('all-works/{works}/edit', [
            WorksController::class,
            'edit',
        ])->name('all-works.edit');
        Route::put('all-works/{works}', [
            WorksController::class,
            'update',
        ])->name('all-works.update');
        Route::delete('all-works/{works}', [
            WorksController::class,
            'destroy',
        ])->name('all-works.destroy');

        Route::get('all-tasks', [TasksController::class, 'index'])->name(
            'all-tasks.index'
        );
        Route::post('all-tasks', [TasksController::class, 'store'])->name(
            'all-tasks.store'
        );
        Route::get('all-tasks/create', [
            TasksController::class,
            'create',
        ])->name('all-tasks.create');
        Route::get('all-tasks/{tasks}', [TasksController::class, 'show'])->name(
            'all-tasks.show'
        );
        Route::get('all-tasks/{tasks}/edit', [
            TasksController::class,
            'edit',
        ])->name('all-tasks.edit');
        Route::put('all-tasks/{tasks}', [
            TasksController::class,
            'update',
        ])->name('all-tasks.update');
        Route::delete('all-tasks/{tasks}', [
            TasksController::class,
            'destroy',
        ])->name('all-tasks.destroy');
    });

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>horario3</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    {{--  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">  --}}

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/notyf.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/ionicons.min.css') }}" rel="stylesheet">




    <!-- Icons -->
    {{--  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css">  --}}
    {{--  <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">  --}}

    {{--  <script src="https://cdnjs.cloudflare.com/ajax/libs/turbolinks/5.2.0/turbolinks.js" integrity="sha512-G3jAqT2eM4MMkLMyQR5YBhvN5/Da3IG6kqgYqU9zlIH4+2a+GuMdLb5Kpxy6ItMdCfgaKlo2XFhI0dHtMJjoRw==" crossorigin="anonymous"></script>  --}}

     <script src="{{ asset('js/turbolinks.js') }}" integrity="sha512-G3jAqT2eM4MMkLMyQR5YBhvN5/Da3IG6kqgYqU9zlIH4+2a+GuMdLb5Kpxy6ItMdCfgaKlo2XFhI0dHtMJjoRw==" crossorigin="anonymous"></script>




    @livewireStyles
    <script src="{{ asset('js/alpine.min.js') }}" defer></script>
    {{--  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>  --}}
</head>
<body>
    <div id="app">
        @include('layouts.nav')

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    @stack('modals')

    @livewireScripts
    <script src="{{ asset('js/livewire-turbolinks.js') }}" data-turbolinks-eval="false" data-turbo-eval="false"></script>
    {{--  <script src="https://cdn.jsdelivr.net/gh/livewire/turbolinks@v0.1.x/dist/livewire-turbolinks.js" data-turbolinks-eval="false" data-turbo-eval="false"></script>  --}}

    @stack('scripts')
 <script src="{{ asset('js/notyf.min.js') }}"></script>
     <script src="{{ asset('js/jquery.min.js') }}" defer></script>
     {{--  <script src="{{ asset('js/jquery.form.min.js') }}" defer></script>  --}}

 {{--  <script src="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js"></script>  --}}

    @if (session()->has('success'))
    <script>
        const notyf = new Notyf({dismissible: true})
        notyf.success('{{ session('success') }}')
    </script>
    @endif

    <script>
        /* Simple Alpine Image Viewer */
        function imageViewer(src = '') {
            return {
                imageUrl: src,

                refreshUrl() {
                    this.imageUrl = this.$el.getAttribute("image-url")
                },

                fileChosen(event) {
                    this.fileToDataUrl(event, src => this.imageUrl = src)
                },

                fileToDataUrl(event, callback) {
                    if (! event.target.files.length) return

                    let file = event.target.files[0],
                        reader = new FileReader()

                    reader.readAsDataURL(file)
                    reader.onload = e => callback(e.target.result)
                },
            }
        }
    </script>

<script src="{{ asset('js/task.js') }}"></script>



</body>
</html>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm p-2">
    <div class="container">
        
        <a class="navbar-brand text-primary font-weight-bold text-uppercase" href="{{ url('/') }}">
            horario3
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                @auth
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('home') }}">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            Apps <span class="caret"></span>
                        </a>
                        
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            @can('view-any', App\Models\User::class)
                            <a class="dropdown-item" href="{{ route('users.index') }}">Users</a>
                            @endcan
                            @can('view-any', App\Models\Clientes::class)
                            <a class="dropdown-item" href="{{ route('all-clientes.index') }}">Clientes</a>
                            @endcan
                            @can('view-any', App\Models\Works::class)
                            <a class="dropdown-item" href="{{ route('all-works.index') }}">Works</a>
                            @endcan
                            @can('view-any', App\Models\Tasks::class)
                            <a class="dropdown-item" href="{{ route('all-tasks.index') }}">Tasks</a>
                            @endcan
                        </div>

                    </li>
                    @if (Auth::user()->can('view-any', Spatie\Permission\Models\Role::class) || 
                        Auth::user()->can('view-any', Spatie\Permission\Models\Permission::class))
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            Access Management <span class="caret"></span>
                        </a>
                        
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            @can('view-any', Spatie\Permission\Models\Role::class)
                            <a class="dropdown-item" href="{{ route('roles.index') }}">Roles</a>
                            @endcan

                            @can('view-any', Spatie\Permission\Models\Permission::class)
                            <a class="dropdown-item" href="{{ route('permissions.index') }}">Permissions</a>
                            @endcan
                        </div>
                    </li>
                    @endif
                @endauth
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>